package com.emcef.model.Facture;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Vector;

public class Facture_selon_specification {
	private int _id;
	private Date _date_time;
	private Integer _id_document;
	private Integer _id_fichier;
	private String _type;
	private String _type_document;
	private String _type_machine;
	private Date _date_requette;
	private int _numero_execution;
	private Date _info_date;
	private String _ifu;
	private BigDecimal _taux_tax_a;
	private BigDecimal _taux_tax_b;
	private BigDecimal _taux_tax_c;
	private BigDecimal _taux_tax_d;
	private BigDecimal _total;
	private BigDecimal _total_a;
	private BigDecimal _total_b;
	private BigDecimal _total_c;
	private BigDecimal _total_d;
	private BigDecimal _total_taxable;
	private BigDecimal _taxable_a;
	private BigDecimal _taxable_b;
	private BigDecimal _taxable_c;
	private BigDecimal _taxable_d;
	private BigDecimal _total_tax;
	private BigDecimal _total_tax_a;
	private BigDecimal _total_tax_b;
	private BigDecimal _total_tax_c;
	private BigDecimal _total_tax_d;
	private String _mrc;
	private String _controle_identifaction;
	private Integer _compteur_schema_controleur;
	private Integer _compteur_total_controuleur;
	private Date _date_heure_controleur;
	private Date _date_controleur;
	private String _harchage_document;
	private String _signature_controleur;
	private String _donneecontrole_controleur;
	private String _signaturepublique_controleur;
	private String _nom_commercial;
	private String _adresse1;
	private String _adresse2;
	private String _contact1;
	private String _contact2;
	private String _entete1;
	private String _entete2;
	private String _entete3;
	private String _pieds1;
	private String _pieds2;
	private String _pieds3;
	private String _ifu_client;
	private String _nom_client;
	private String _adresse1_client;
	private String _adresse2_client;
	private String _contact1_client;
	private String _contact2_client;
	private String _payement;
	private BigDecimal _montant_payement;
	private String _operateur;
	private String _reference_remboursement;
	private BigDecimal _aib;
	private BigDecimal _montant_aib;
	private BigDecimal _tax_specifique_a;
	private BigDecimal _tax_specifique_b;
	private BigDecimal _tax_specifique_c;
	private BigDecimal _tax_specifique_d;
	private BigDecimal _total_tax_specifique;
	private Boolean _status;
	private boolean _calcul;
	private BigDecimal _tauxtax_e;
	private BigDecimal _tauxtax_f;
	private BigDecimal _total_e;
	private BigDecimal _total_f;
	private BigDecimal _taxable_e;
	private BigDecimal _taxable_f;
	private BigDecimal _total_tax_e;
	private BigDecimal _total_tax_f;
	private String _adresse3;
	private String _contact3;
	private BigDecimal _tax_specifique_e;
	private BigDecimal _tax_specifique_f;
	public Vector<Article_facture> _article_facture = new Vector<Article_facture>();
}