package com.emcef.model.Rapport;

import com.emcef.model.Machines.Machines_enregistrees;
import java.math.BigDecimal;
import java.util.Date;

public class Rapport_zr {
	private int _id;
	private Date _date_heure;
	private Date _date_heure_rapport;
	private Integer _id_rapport;
	private Integer _cr_rapport;
	private Integer _id_doc;
	private String _ifu;
	private BigDecimal _tauxtax_a;
	private BigDecimal _tauxtax_b;
	private BigDecimal _tauxtax_c;
	private BigDecimal _tauxtax_d;
	private BigDecimal _tauxtax_e;
	private BigDecimal _tauxtax_f;
	private BigDecimal _tauxtax_aib_a;
	private BigDecimal _tauxtax_aid_b;
	private Integer _compte_rapport_journalier;
	private Integer _compte_rapport_change;
	private Integer _compte_vente_normal;
	private Integer _compte_remboursement_normal;
	private Integer _compte_copie_vente;
	private Integer _compte_copie_remboursement_normal;
	private Integer _compte_vente_exportation;
	private Integer _compte_remboursement_exportation;
	private Integer _compte_copie_vente_exportation;
	private Integer _compte_copie_remboursement_exportation;
	private BigDecimal _montant_a;
	private BigDecimal _montant_b;
	private BigDecimal _montant_c;
	private BigDecimal _montant_d;
	private BigDecimal _montant_e;
	private BigDecimal _montant_f;
	private BigDecimal _montant_taxable_a;
	private BigDecimal _montant_taxable_b;
	private BigDecimal _montant_taxable_c;
	private BigDecimal _montant_taxable_d;
	private BigDecimal _montant_taxable_e;
	private BigDecimal _montant_taxable_f;
	private BigDecimal _montant_tax_a;
	private BigDecimal _montant_tax_b;
	private BigDecimal _montant_tax_c;
	private BigDecimal _montant_tax_d;
	private BigDecimal _montant_tax_e;
	private BigDecimal _montant_tax_f;
	private BigDecimal _montant_tax_aib_a;
	private BigDecimal _montant_tax_aib_b;
	private BigDecimal _montant_ts_a;
	private BigDecimal _montant_ts_b;
	private BigDecimal _montant_ts_c;
	private BigDecimal _montant_ts_d;
	private BigDecimal _montant_ts_e;
	private BigDecimal _montant_ts_f;
	private String _sw_version;
	private Date _tr_pen_date;
	private BigDecimal _tr_pen_ta;
	private BigDecimal _tr_pen_tb;
	private BigDecimal _tr_pen_tc;
	private BigDecimal _tr_pen_td;
	private BigDecimal _tr_pen_te;
	private BigDecimal _tr_pen_tf;
	private BigDecimal _tr_pen_aib_a;
	private BigDecimal _tr_pen_aid_b;
	private Date _fw_pen_date;
	private String _fw_pen_current_version;
	private String _fw_pen_new_version;
	public Machines_enregistrees _id_machine_enregistree;
}